-- MySQL Script generated by MySQL Workbench
-- Sat Aug 28 15:57:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema business
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema business
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `business` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `business` ;

-- -----------------------------------------------------
-- Table `business`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `business`.`company` (
  `id` INT NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `business`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `business`.`department` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `department_ibfk_1` (`company_id` ASC),
  CONSTRAINT `department_ibfk_1`
    FOREIGN KEY (`company_id`)
    REFERENCES `business`.`company` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `business`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `business`.`role` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `business`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `business`.`staff` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `company_id` INT NOT NULL,
  `department_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `staff_ibfk_1` (`company_id` ASC),
  INDEX `staff_ibfk_2` (`department_id` ASC),
  INDEX `staff_ibfk_3` (`role_id` ASC),
  CONSTRAINT `staff_ibfk_1`
    FOREIGN KEY (`company_id`)
    REFERENCES `business`.`company` (`id`),
  CONSTRAINT `staff_ibfk_2`
    FOREIGN KEY (`department_id`)
    REFERENCES `business`.`department` (`id`),
  CONSTRAINT `staff_ibfk_3`
    FOREIGN KEY (`role_id`)
    REFERENCES `business`.`role` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `business`.`discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `business`.`discount` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `value` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `business`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `business`.`product` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `price` INT NOT NULL,
  `suggestion_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  `discount_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_ibfk_1` (`suggestion_id` ASC),
  INDEX `product_ibfk_2` (`company_id` ASC),
  INDEX `product_ibfk_3` (`discount_id` ASC),
  CONSTRAINT `product_ibfk_1`
    FOREIGN KEY (`suggestion_id`)
    REFERENCES `business`.`suggestion` (`id`),
  CONSTRAINT `product_ibfk_2`
    FOREIGN KEY (`company_id`)
    REFERENCES `business`.`company` (`id`),
  CONSTRAINT `product_ibfk_3`
    FOREIGN KEY (`discount_id`)
    REFERENCES `business`.`discount` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `business`.`suggestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `business`.`suggestion` (
  `id` INT NOT NULL,
  `staff_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `amount` INT NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `suggestion_ibfk_1` (`staff_id` ASC),
  INDEX `product_id` (`product_id` ASC),
  CONSTRAINT `suggestion_ibfk_1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `business`.`staff` (`id`),
  CONSTRAINT `suggestion_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `business`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `business`.`buy_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `business`.`buy_product` (
  `id` INT NOT NULL,
  `suggestion_id` INT NOT NULL,
  `amount` INT NOT NULL,
  `price` INT NOT NULL,
  `total` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `buy_product_ibfk_1` (`suggestion_id` ASC),
  CONSTRAINT `buy_product_ibfk_1`
    FOREIGN KEY (`suggestion_id`)
    REFERENCES `business`.`suggestion` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `business`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `business`.`payment` (
  `id` INT NOT NULL,
  `company_id` INT NOT NULL,
  `buy_product_id` INT NOT NULL,
  `vat` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `payment_ibfk_1` (`company_id` ASC),
  INDEX `payment_ibfk_2` (`buy_product_id` ASC),
  CONSTRAINT `payment_ibfk_1`
    FOREIGN KEY (`company_id`)
    REFERENCES `business`.`company` (`id`),
  CONSTRAINT `payment_ibfk_2`
    FOREIGN KEY (`buy_product_id`)
    REFERENCES `business`.`buy_product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `business`.`assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `business`.`assignment` (
  `id` INT NOT NULL,
  `company_id` INT NOT NULL,
  `payment_id` INT NOT NULL,
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `assignment_ibfk_1` (`company_id` ASC),
  INDEX `assignment_ibfk_2` (`payment_id` ASC),
  INDEX `assignment_ibfk_3` (`staff_id` ASC),
  CONSTRAINT `assignment_ibfk_1`
    FOREIGN KEY (`company_id`)
    REFERENCES `business`.`company` (`id`),
  CONSTRAINT `assignment_ibfk_2`
    FOREIGN KEY (`payment_id`)
    REFERENCES `business`.`payment` (`id`),
  CONSTRAINT `assignment_ibfk_3`
    FOREIGN KEY (`staff_id`)
    REFERENCES `business`.`staff` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `business`.`privilege`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `business`.`privilege` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `business`.`role_privilege`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `business`.`role_privilege` (
  `id` INT NOT NULL,
  `role_id` INT NOT NULL,
  `privilege_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `role_privilege_ibfk_1` (`role_id` ASC),
  INDEX `role_privilege_ibfk_2` (`privilege_id` ASC),
  CONSTRAINT `role_privilege_ibfk_1`
    FOREIGN KEY (`role_id`)
    REFERENCES `business`.`role` (`id`),
  CONSTRAINT `role_privilege_ibfk_2`
    FOREIGN KEY (`privilege_id`)
    REFERENCES `business`.`privilege` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
